version: "3.7"

services:
  django:
    build: .
    command: bash -c "service cron start && cd app && python ./manage.py crontab add && python ./manage.py runserver 0:8001"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8001:8001
